### ISSUE TITLE
css not rendering on github page

### ISSUE THREAD

**Issue by yifan97** [GerganaTsirkova/advokativanov#1]
Hey I came across your previous issue with css. I had the same issue that the website ran fine on localhost but there was no styling on github page. I have tried set the baseurl to my own repository.

Did you manage to solve this issue?

**Comment by GerganaTsirkova** [comment]
Hello, yes I've solved it. It was just a Github issue. When I changed the
baseurl in the config.yml (baseurl: "reponame/") file it took almost a day
and a half of Github to public the changes.




-------------------------------------

П.П. Направи си сайт! Лесно е. Всичко нужно е на едно място в СуперХостинг.БГ!
 https://www.superhosting.bg/?utm_source=mbg&utm_medium=cpm&utm_content=mail_footer&utm_campaign=newuser_campaign2019

**Comment by GerganaTsirkova** [comment]
baseurl: "/reponame"
baseurl: ""


The above is in my config.yml file. When I want to upload changes to my
github repo I put '#' in front of the baseurl with empty "". Then I start
gulp and make the commit and push the files. When this is done you remove
"#" in front of the baseurl whith the empty "" and put it front of the
other one. Then again start the local server with the gulp
command(everytime you make changes in the cofig file you must restart the
server) and you can continue working locally.




-------------------------------------

П.П. Знаеш ли, че можеш да си направиш сайт бързо и лесно? Нужно ти е по-малко от час и е готов. Научи как на www.superhosting.bg
 https://www.superhosting.bg/site-builder.php?utm_source=mbg&utm_medium=cpm&utm_content=mail_footer&utm_campaign=newuser_campaign2019
